site_name: FoPM Learning Program &ndash; Institute of Astronomy
site_description: FoPM Learning Program at Institute of Astronomy
site_author: Ryou Ohsawa
copyright: Ryou Ohsawa 2021
nav:
  - トップページ: index.md
  - 実習テキスト:
    - MCMC 入門:
      - mcmc/index.md
      - mcmc/generate_random_variables.md
      - mcmc/static_monte_carlo.md
      - mcmc/markov_chain.md
      - mcmc/references.md
  - FoPM Home: https://www.s.u-tokyo.ac.jp/ja/FoPM/
  - GitHub repository: https://github.com/FoPM-Astronomy-UTokyo/course
theme:
  name: 'material'
  language: 'en'
  palette:
    scheme: default
    primary: teal
    accent: deep orange
extra_css:
  - css/config_local.css
extra_javascript:
  - js/config_mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - extra
  - admonition
  - smarty
  - sane_lists
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: True
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search:
      lang: 'ja'
#  - pdf-export
#  - with-pdf
