site_name: FoPM Practical Course &ndash; Institute of Astronomy
site_description: FoPM Practical Course at Institute of Astronomy
site_author: Ryou Ohsawa
copyright: Ryou Ohsawa 2021
nav:
  - トップページ: index.md
  - 実習テキスト:
    - MCMC 入門:
      - mcmc/index.md
      - mcmc/generate_random_variables.md
      - mcmc/static_monte_carlo.md
      - mcmc/markov_chain.md
      - mcmc/scratchbuild_mcmc.md
      - mcmc/chain_convergence.md
      - mcmc/linear_regression.md
      - mcmc/censored_regression.md
      - mcmc/logistic_regression.md
      - mcmc/count_model.md
      - mcmc/references.md
  - FoPM Home: https://www.s.u-tokyo.ac.jp/ja/FoPM/
  - GitHub repository: https://github.com/FoPM-Astronomy-UTokyo/course
theme:
  name: 'material'
  icon:
    logo: logo
  language: 'en'
  palette:
    scheme: default
    primary: teal
    accent: deep orange
  features:
    - navigation.instant
    - header.autohide
extra_css:
  - css/config_local.css
extra_javascript:
  - js/config_mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - extra
  - admonition
  - smarty
  - sane_lists
  - meta
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
      check_paths: True
  - pymdownx.arithmatex:
      generic: true
plugins:
  - search:
      lang: 'ja'
#  - pdf-export
#  - with-pdf
